-- Initial Supabase schema for Contents View.
-- This migration preserves the current UI and feature surface while preparing
-- Supabase Auth, bookmarks, user API keys, and cached collection data.

create extension if not exists pgcrypto;

do $$
begin
  create type public.app_role as enum ('user', 'admin');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.approval_status as enum ('pending', 'approved', 'rejected');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.api_key_test_status as enum ('untested', 'success', 'failed');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.youtube_content_type as enum ('video', 'shorts');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  member_no bigint generated by default as identity unique,
  name text,
  email text,
  avatar_url text,
  role public.app_role not null default 'user',
  approval_status public.approval_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in_at timestamptz
);

create table if not exists public.memberships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  plan text not null default 'free',
  status text not null default 'active',
  started_at timestamptz not null default now(),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create table if not exists public.user_api_keys (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null,
  encrypted_key text not null,
  masked_key text,
  test_status public.api_key_test_status not null default 'untested',
  test_error text,
  last_tested_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider)
);

create table if not exists public.youtube_bookmarks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  video_id text not null,
  content_type public.youtube_content_type not null,
  title text not null,
  thumbnail_url text,
  channel_id text,
  channel_title text,
  channel_thumbnail_url text,
  video_url text,
  duration text,
  view_count text,
  published_at text,
  created_at timestamptz not null default now(),
  unique (user_id, video_id, content_type)
);

create table if not exists public.sources (
  id text primary key,
  kind text not null,
  display_name text not null,
  source_url text,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.collection_runs (
  id uuid primary key default gen_random_uuid(),
  source_id text references public.sources(id) on delete set null,
  kind text not null,
  status text not null default 'started',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  item_count integer not null default 0,
  error_message text,
  meta jsonb not null default '{}'::jsonb
);

create table if not exists public.news_items (
  id uuid primary key default gen_random_uuid(),
  source_id text references public.sources(id) on delete set null,
  category text not null default 'all',
  title text not null,
  link text not null,
  source_name text,
  thumbnail_url text,
  summary text,
  published_at timestamptz,
  collected_at timestamptz not null default now(),
  raw jsonb not null default '{}'::jsonb,
  unique (link)
);

create table if not exists public.community_posts (
  id uuid primary key default gen_random_uuid(),
  source_id text references public.sources(id) on delete set null,
  community text not null,
  rank integer,
  title text not null,
  author text,
  link text,
  view_count integer,
  reaction_count integer,
  comment_count integer,
  posted_at timestamptz,
  collected_at timestamptz not null default now(),
  raw jsonb not null default '{}'::jsonb,
  unique (community, link)
);

create index if not exists news_items_category_published_idx
  on public.news_items (category, published_at desc nulls last);

create index if not exists community_posts_source_collected_idx
  on public.community_posts (source_id, collected_at desc);

create index if not exists collection_runs_kind_started_idx
  on public.collection_runs (kind, started_at desc);

alter table public.profiles enable row level security;
alter table public.memberships enable row level security;
alter table public.user_api_keys enable row level security;
alter table public.youtube_bookmarks enable row level security;
alter table public.sources enable row level security;
alter table public.collection_runs enable row level security;
alter table public.news_items enable row level security;
alter table public.community_posts enable row level security;

create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "memberships_select_own"
  on public.memberships for select
  using (auth.uid() = user_id);

create policy "api_keys_select_own"
  on public.user_api_keys for select
  using (auth.uid() = user_id);

create policy "api_keys_insert_own"
  on public.user_api_keys for insert
  with check (auth.uid() = user_id);

create policy "api_keys_update_own"
  on public.user_api_keys for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "api_keys_delete_own"
  on public.user_api_keys for delete
  using (auth.uid() = user_id);

create policy "youtube_bookmarks_select_own"
  on public.youtube_bookmarks for select
  using (auth.uid() = user_id);

create policy "youtube_bookmarks_insert_own"
  on public.youtube_bookmarks for insert
  with check (auth.uid() = user_id);

create policy "youtube_bookmarks_delete_own"
  on public.youtube_bookmarks for delete
  using (auth.uid() = user_id);

create policy "sources_public_read"
  on public.sources for select
  using (is_enabled = true);

create policy "news_items_public_read"
  on public.news_items for select
  using (true);

create policy "community_posts_public_read"
  on public.community_posts for select
  using (true);

create policy "collection_runs_service_only"
  on public.collection_runs for all
  using (false)
  with check (false);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, email, avatar_url, approval_status)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    new.email,
    new.raw_user_meta_data->>'avatar_url',
    'approved'
  )
  on conflict (id) do update
    set
      name = excluded.name,
      email = excluded.email,
      avatar_url = excluded.avatar_url,
      last_signed_in_at = now(),
      updated_at = now();

  insert into public.memberships (user_id, plan, status)
  values (new.id, 'free', 'active')
  on conflict do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update on auth.users
  for each row execute function public.handle_new_user();

insert into public.sources (id, kind, display_name, source_url)
values
  ('google-news', 'news', 'Google News', 'https://news.google.com/rss'),
  ('dcinside', 'community', 'DC Inside', 'https://www.dcinside.com'),
  ('ppomppu', 'community', 'Ppomppu', 'https://www.ppomppu.co.kr'),
  ('natepann', 'community', 'Nate Pann', 'https://pann.nate.com'),
  ('ruliweb', 'community', 'Ruliweb', 'https://bbs.ruliweb.com'),
  ('inven', 'community', 'Inven', 'https://www.inven.co.kr'),
  ('bobaedream', 'community', 'Bobaedream', 'https://www.bobaedream.co.kr'),
  ('humoruniv', 'community', 'Humoruniv', 'https://web.humoruniv.com')
on conflict (id) do nothing;
